using System;
using User.Models;
using User.Api;
using User.Tools;

namespace User.Interaction
{
    public class UserInteraction
    {
        static readonly ApiInteraction api = new ApiInteraction();
        static readonly WebScrapper scrapper = new WebScrapper();

        private bool continuation = true;

        public async Task BeginUserInteraction()
        {
            while (continuation)
            {
                await HandleUserInput();
            }
        }

        private async Task HandleUserInput()
        {
            string user_response = DisplayOptions();

            switch (user_response)
            {
                case "1":
                    List<Flashcard> allCards = await api.ViewCards();

                    foreach (Flashcard card in allCards)
                    {
                        System.Console.WriteLine($"\n{card.Word,3} {"|",10} {card.Furigana,25} {"|",10} {card.Definition,25} {"|",10} {card.Example,25} {"|",10} {card.Difficulty,25} {"|",10} {card.Last_Reviewed,25}\n");
                    }
                    break;

                case "2":
                    System.Console.WriteLine("\nCreating new card...\n");
                    Flashcard newCard = await PopulateCard();

                    string createResult = await api.CreateNewCard(newCard);

                    System.Console.WriteLine($"Create Result: {createResult}");
                    break;

                case "3":
                    System.Console.WriteLine("\n Type a word you would like to delete");
                    string wordToDelete = System.Console.ReadLine() ?? throw new NullReferenceException(nameof(wordToDelete));

                    string deleteResult = await api.DeleteCard(wordToDelete.Trim());

                    System.Console.WriteLine($"Delete result: {deleteResult}");
                    break;

                case "0":
                    System.Console.WriteLine("Terminating...");
                    continuation = false;
                    break;

                default:
                    System.Console.WriteLine("Unrecognized command");
                    break;
            }
        }

        private string DisplayOptions()
        {
            System.Console.WriteLine("[1] View all cards");
            System.Console.WriteLine("[2] Add a new card");
            System.Console.WriteLine("[3] Delete a card");
            System.Console.WriteLine("[0] End");

            string user_response = System.Console.ReadLine() ?? throw new NullReferenceException(nameof(user_response));

            return user_response;
        }

        private async Task<Flashcard> PopulateCard()
        {
            System.Console.Write("Word:");
            string word = System.Console.ReadLine() ?? throw new NullReferenceException(nameof(word));

            System.Console.Write("\nFurigana:");
            string? furigana = System.Console.ReadLine();

            System.Console.Write("\nDefinition:");
            string definition = System.Console.ReadLine() ?? throw new NullReferenceException(nameof(definition));

            System.Console.WriteLine("\n Would you like to choose an example sentence from an autogenerated list? Y/N");
            string autoGenerateExampleResponse = System.Console.ReadLine() ?? throw new NullReferenceException(nameof(autoGenerateExampleResponse));

            string? example = "";
            if (autoGenerateExampleResponse.ToLower() == "y")
            {
                System.Console.WriteLine("\n Select one of the following:");
                string[] sentenceChoices = await scrapper.ScrapSentence(word);

                int sentenceNum = 0;
                foreach(string i in sentenceChoices)
                {
                    System.Console.WriteLine($"[{sentenceNum}] {i}");
                    sentenceNum++;
                }

                string userSelection = System.Console.ReadLine() ?? throw new NullReferenceException(nameof(userSelection));

                switch (userSelection)
                {
                    case "0":
                        example = sentenceChoices[0];
                        break;
                    case "1":
                        example = sentenceChoices[1];
                        break;
                    case "2":
                        example = sentenceChoices[2];
                        break;
                    default:
                        System.Console.WriteLine("Choice not recognized");
                        break;
                }
            }
            else
            {
                System.Console.Write("\nExample:");
                example = System.Console.ReadLine();
            }

            string defaultLastReview = DateTime.Today.ToString("d"); 
            Flashcard card = new Flashcard(word, furigana, definition, example, 1, defaultLastReview);

            return card;
        }
    }
}

